routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::guest()) {
        return redirect()->route('login');
    } else {
        return redirect()->route(Auth::user()->role . '.dashboard');
    }
});

Auth::routes();

//administrator
Route::group(['prefix' => '/administrator', 'as' => 'admin.', 'middleware' => ['admin']], function () {

    //dashboard
    Route::get('/', 'AdminController@dashboard')->name('dashboard');

    //complaint
    Route::resource('/complaint', 'ComplaintController');

    //people
    Route::resource('/people', 'PeopleController');

    //officer
    Route::resource('/officer', 'OfficerController');

    //report
    Route::get('/report', 'AdminController@report')->name('report');

});

//officer
Route::group(['prefix' => '/officer', 'as' => 'officer.', 'middleware' => ['officer']], function () {

    //dashboard
    Route::get('/', 'OfficerController@dashboard')->name('dashboard');

    //complaint
    Route::resource('/complaint', 'ComplaintController');

});

//people
Route::group(['prefix' => '/people', 'as' => 'people.', 'middleware' => ['people']], function () {

    //dashboard
    Route::get('/', 'PeopleController@dashboard')->name('dashboard');

    //complaint
    Route::resource('/complaint', 'ComplaintController');

});

app/Officer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Officer extends Model
{
    //
    protected $guarded = [];

    public function user () {
        return $this->belongsTo('App\User');
    }

    public function responses () {
        return $this->hasMany('App\Response');
    }
}

app/Http/Controllers/OfficerController.php
<?php

namespace App\Http\Controllers;

use App\Officer;
use App\User;
use Illuminate\Http\Request;
use Validator;
use Auth;

class OfficerController extends Controller
{
    public function __construct(Officer $officer, User $user)
    {
        $this->officer = $officer;
        $this->user = $user;
    }

    public function dashboard () {
        return view('officer.dashboard');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $officers = $this->user->where('role', 'officer')->orderBy('username', 'asc')->get()->map(function ($user) {
            return $user->officer;
        });

        //
        return view('officer.index', [
            'officers' => $officers
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = Validator::make($request->all(), [
            'username' => 'required|unique:users,username',
            'name' => 'required',
            'phone' => 'required',
            'photo' => 'mimes:jpg,png,jpeg',
            'password' => 'required|confirmed'
        ]);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withErrors($validation)->withInput($request->all());

        // upload proof
        if ($request->file('photo')) {
            $photo = $request->file('photo')->store('public/officers');
        } else {
            $photo = 'public/officers/default.jpg';
        }

        // validation success
        $user = $this->user->create([
            'username' => $request->username,
            'password' => bcrypt($request->password),
            'role' => 'officer'
        ]);;
        $officer = $this->officer->create([
            'name' => $request->name,
            'phone' => $request->phone,
            'photo' => $photo,
            'user_id' => $user->id
        ]);

        // if success
        if ($officer) {
            return redirect()->back()->with('msg', 'Officer created successful');
        } else {
            return redirect()->back()->withErrors(['title' => 'Something errors'])->withInput($request->all());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Officer  $officer
     * @return \Illuminate\Http\Response
     */
    public function show(Officer $officer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Officer  $officer
     * @return \Illuminate\Http\Response
     */
    public function edit(Officer $officer)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Officer  $officer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Officer $officer)
    {
        //
        //
        $validation = Validator::make($request->all(), [
            'username' => 'required|unique:users,username,' . $officer->user->id,
            'name' => 'required',
            'phone' => 'required',
            'photo' => 'mimes:jpg,png,jpeg'
        ]);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withErrors($validation)->withInput($request->all());

        // upload proof
        if ($request->file('photo')) {
            $photo = $request->file('photo')->store('public/officers');
        } else {
            $photo = $officer->photo;
        }

        // validation success
        $update = $officer->update([
            'name' => $request->name,
            'phone' => $request->phone,
            'photo' => $photo
        ]);
        $officer->user()->update([
            'username' => $request->username
        ]);

        // if success
        if ($update) {
            return redirect()->back()->with('msg', 'Officer updated successful');
        } else {
            return redirect()->back()->withErrors(['title' => 'Something errors'])->withInput($request->all());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Officer  $officer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Officer $officer)
    {
        //
        if ($officer->responses->count() > 0) {
            return response()->json(['message' => 'Officer have complaints are response'], 401);
        }

        $officer->user()->delete();

        return response()->json(['message' => 'Officer deleted successful'], 200);
    }
}

resources/views/officer/dashboard.blade.php
@extends('layouts.admin')

@section('title')
    Dashboard
@endsection

@section('dashboard')
    active
@endsection

@section('css')
@endsection

@section('js')
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                <span class="page-title-icon bg-gradient-primary text-white mr-2">
                  <i class="mdi">home</i>
                </span> Dashboard </h3>
            <nav aria-label="breadcrumb">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                        <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="row">

            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 grid-margin stretch-card">
                <div class="card card-statistics">
                    <div class="card-body">
                        <div class="clearfix">
                            <div class="float-left">
                                <i class="mdi text-danger icon-lg">comment</i>
                            </div>
                            <div class="float-right">
                                <p class="mb-0 text-right">Complaints</p>
                                <div class="fluid-container">
                                    <h3 class="font-weight-medium text-right mb-0">{{\App\Complaint::where('status', '!=', 1)->count()}}</h3>
                                </div>
                            </div>
                        </div>
                        <p class="text-muted mt-3 mb-0">
                            <i class="mdi mdi-alert-octagon mr-1" aria-hidden="true"></i> All of complaints </p>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 grid-margin stretch-card">
                <div class="card card-statistics">
                    <div class="card-body">
                        <div class="clearfix">
                            <div class="float-left">
                                <i class="mdi text-warning icon-lg">inbox</i>
                            </div>
                            <div class="float-right">
                                <p class="mb-0 text-right">Received</p>
                                <div class="fluid-container">
                                    <h3 class="font-weight-medium text-right mb-0">{{\App\Complaint::whereStatus(2)->count()}}</h3>
                                </div>
                            </div>
                        </div>
                        <p class="text-muted mt-3 mb-0">
                            <i class="mdi mdi-bookmark-outline mr-1" aria-hidden="true"></i> complaints are received </p>
                    </div>
                </div>
            </div>

            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 grid-margin stretch-card">
                <div class="card card-statistics">
                    <div class="card-body">
                        <div class="clearfix">
                            <div class="float-left">
                                <i class="mdi text-success icon-lg">done_all</i>
                            </div>
                            <div class="float-right">
                                <p class="mb-0 text-right">Responded</p>
                                <div class="fluid-container">
                                    <h3 class="font-weight-medium text-right mb-0">{{\App\Complaint::whereStatus(3)->count()}}</h3>
                                </div>
                            </div>
                        </div>
                        <p class="text-muted mt-3 mb-0">
                            <i class="mdi mdi-calendar mr-1" aria-hidden="true"></i> complaints are responded </p>
                    </div>
                </div>
            </div>



            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 grid-margin stretch-card">
                <div class="card review-card">
                    <div class="card-header header-sm d-flex justify-content-between align-items-center">
                        <h4 class="card-title mb-0">New received complaints</h4>
                        <div class="wrapper d-flex align-items-center">
                            <div class="dropdown">
                                <button class="btn btn-transparent icon-btn pr-0" type="button" id="dropdownMenuIconButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="mdi">more_vert</i>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuIconButton1" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 46px, 0px);">
                                    <a class="dropdown-item" href="{{route('people.complaint.index')}}">Today</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body no-gutter">

                        @foreach(\App\Complaint::where('status', '2')->orderBy('created_at', 'desc')->skip(0)->take(5)->get() as $complaint)
                            <div class="list-item">
                                <div class="preview-image">
                                    <img class="img-sm rounded-circle" src="{{URL::asset('storage/app/' . $complaint->people->photo)}}" alt="profile image">
                                </div>
                                <div class="content">
                                    <div class="d-flex align-items-center">
                                        <h6 class="product-name">{{$complaint->people->name}}</h6>
                                        <small class="time ml-3 d-none d-sm-block">{{$complaint->created_at->diffForHumans()}}</small>
                                        <div class="ml-auto">
                                            <a href="{{route(Auth::user()->role . '.complaint.show', ['complaint' => $complaint->id])}}" class="btn btn-primary btn-sm" style="display: inline;">View complaint</a>
                                        </div>
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <p class="user-name">Say :</p>
                                        <p class="review-text d-block">{{$complaint->title}}</p>
                                    </div>
                                </div>
                            </div>
                        @endforeach

                        @if(\App\Complaint::where('status', '2')->orderBy('created_at', 'desc')->skip(0)->take(5)->count() == 0)
                            No data
                        @endif
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/officer/index.blade.php
@extends('layouts.admin')

@section('title')
        Manage Officers
@endsection

@section('officers')
    active
@endsection

@section('css')
    <link rel="stylesheet" href="{{asset('assets/vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}">
@endsection

@section('js')
    <script src="{{asset('assets/vendors/datatables.net/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>
    <script src="{{asset('assets/js/data-table.js')}}"></script>
    <script src="{{asset('assets/vendors/sweetalert/sweetalert.min.js')}}"></script>

    <script>
        $('body').delegate('#edit', 'click',  function (e) {
            e.preventDefault();

            let username = $(this).parents('tr').find('#td-username').text();
            let name = $(this).parents('tr').find('#td-name').text();
            let phone = $(this).parents('tr').find('#td-phone').text();
            let photo = $(this).parents('tr').find('#td-img img').attr('src');

            $('#username').val(username);
            $('#fullname').val(name);
            $('#phone').val(phone);
            $('#preview').attr('src', photo);
            $('#modal-edit').attr('action', $(this).attr('href'));

            $('#modal-edit').modal('show');
        });

        $('body').delegate('#delete', 'click',  function (e) {
            e.preventDefault();

            swal({
                title: 'Are you sure?',
                text: "Do you want to delete it?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3f51b5',
                cancelButtonColor: '#ff4081',
                confirmButtonText: 'Great ',
                buttons: {
                    cancel: {
                        text: "Cancel",
                        value: null,
                        visible: true,
                        className: "btn btn-danger",
                        closeModal: true,
                    },
                    confirm: {
                        text: "OK",
                        value: true,
                        visible: true,
                        className: "btn btn-primary",
                        closeModal: true
                    }
                }
            }).then((result) => {
                if (result) {
                    let token = $('meta[name="csrf-token"]').attr('content');
                    let url = $(this).attr('href');
                    $.ajax({
                        url,
                        method: 'post',
                        data: {_token: token, _method: 'delete'},
                        success: function (res) {
                            swal({
                                title: 'Successful',
                                text: res.message,
                                icon: 'success',
                                button: {
                                    text: "Continue",
                                    value: true,
                                    visible: true,
                                    className: "btn btn-primary"
                                }
                            }).then((result) => {
                               location.reload();
                            });
                        },
                        error: function (res) {
                            swal({
                                title: 'Something error',
                                text: res.responseJSON.message,
                                icon: 'error',
                                button: {
                                    text: "Continue",
                                    value: true,
                                    visible: true,
                                    className: "btn btn-primary"
                                }
                            })
                        }
                    })

                }
            })
        });

        $('#new').click(function (e) {
            e.preventDefault();

            $('#modal-add').modal('show');
        });

        @if(session('msg'))
            swal({
                title: 'Successful',
                text: '{{session('msg')}}',
                icon: 'success',
                button: {
                    text: "Continue",
                    value: true,
                    visible: true,
                    className: "btn btn-primary"
                }
            })
        @endif

        @if($errors->any())
            let text = "";
            @foreach($errors->all() as $i => $error)
                text += '{{$error}} ';
            @endforeach
            swal({
                title: 'Something error',
                text: text,
                html: true,
                icon: 'error',
                button: {
                    text: "Continue",
                    value: true,
                    visible: true,
                    className: "btn btn-primary"
                }
            })
        @endif
    </script>
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Manage Officers
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{route(Auth::user()->role . '.dashboard')}}">Dashboard</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Manage Officers
                    </li>
                </ol>
            </nav>
        </div>
        <button type="button" id="new" class="btn btn-gradient-primary mb-4 d-flex align-items-center"><i class="mdi mr-1">add</i> Add a officer</button>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Data officers</h4>
                <div class="row">
                    <div class="col-12">
                        <table id="order-listing" class="table">
                            <thead>
                            <tr>
                                <th class="text-center">Order #</th>
                                <th>Username</th>
                                <th>Fullname</th>
                                <th class="text-center">Phone</th>
                                <th class="text-center">Created at</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($officers as $i => $officer)
                                <tr>
                                    <td class="text-center">{{$i+1}}</td>
                                    <td id="td-username">{{$officer->user->username}}<div id="td-img" style="display: none;"><img src="{{URL::asset('storage/app/' . $officer->photo)}}" alt=""></div></td>
                                    <td id="td-name">{{$officer->name}}</td>
                                    <td class="text-center" id="td-phone">{{$officer->phone}}</td>
                                    <td class="text-center">{{$officer->created_at->diffForHumans()}}</td>
                                    <td class="text-center">
                                        <a href="{{route('admin.officer.update', ['officer' => $officer->id])}}" id="edit" class="btn btn-warning mr-2">Edit</a>
                                        <a href="{{route('admin.officer.destroy', ['officer' => $officer->id])}}" id="delete" class="btn btn-danger">Delete</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <form class="modal fade" id="modal-add" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" action="{{route('admin.officer.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add a officer</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="fullname-a">Fullname</label>
                            <input type="text" name="name" id="fullname-a" class="form-control" value="{{old('name')}}">
                        </div>
                        <div class="form-group">
                            <label for="phone-a">Phone</label>
                            <input type="text" name="phone" id="phone-a" class="form-control" value="{{old('phone')}}">
                        </div>
                        <div class="form-group">
                            <label for="photo-a">Photo</label>
                            <input type="file" name="photo" id="photo-a" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="username-a">Username</label>
                            <input type="text" name="username" id="username-a" class="form-control" value="{{old('username')}}">
                        </div>
                        <div class="form-group">
                            <label for="password-a">Password</label>
                            <input type="password" name="password" id="password-a" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password_confirmation-a">Password Confirmation</label>
                            <input type="password" name="password_confirmation" id="password_confirmation-a" class="form-control">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">
                            Save
                        </button>
                        <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
        </form>
        <form class="modal fade" id="modal-edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" action="" method="post" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Edit officer</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" name="username" id="username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="fullname">Fullname</label>
                            <input type="text" name="name" id="fullname" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="phone">Phone</label>
                            <input type="text" name="phone" id="phone" class="form-control">
                        </div>
                        <div class="form-group">
                            <img src="" id="preview" class="mb-4" style="width: 200px; display: block">
                            <label for="photo">Change Photo</label>
                            <input type="file" name="photo" id="photo" class="form-control">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">
                            Update
                        </button>
                        <button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
        </form>
@endsection