routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::guest()) {
        return redirect()->route('login');
    } else {
        return redirect()->route(Auth::user()->role . '.dashboard');
    }
});

Auth::routes();

//administrator
Route::group(['prefix' => '/administrator', 'as' => 'admin.', 'middleware' => ['admin']], function () {

    //dashboard
    Route::get('/', 'AdminController@dashboard')->name('dashboard');

    //complaint
    Route::resource('/complaint', 'ComplaintController');

    //people
    Route::resource('/people', 'PeopleController');

    //officer
    Route::resource('/officer', 'OfficerController');

    //report
    Route::get('/report', 'AdminController@report')->name('report');

});

//officer
Route::group(['prefix' => '/officer', 'as' => 'officer.', 'middleware' => ['officer']], function () {

    //dashboard
    Route::get('/', 'OfficerController@dashboard')->name('dashboard');

    //complaint
    Route::resource('/complaint', 'ComplaintController');

});

//people
Route::group(['prefix' => '/people', 'as' => 'people.', 'middleware' => ['people']], function () {

    //dashboard
    Route::get('/', 'PeopleController@dashboard')->name('dashboard');

    //complaint
    Route::resource('/complaint', 'ComplaintController');

});

app/People.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class People extends Model
{
    //
    protected $guarded = [];

    public function user () {
        return $this->belongsTo('App\User');
    }

    public function complaints () {
        return $this->hasMany('App\Complaint');
    }
}

app/Http/Controllers/PeopleController.php
<?php

namespace App\Http\Controllers;

use App\People;
use Illuminate\Http\Request;
use Validator;
use Auth;
use App\User;

class PeopleController extends Controller
{
    public function __construct(People $people, User $user)
    {
        $this->people = $people;
        $this->user = $user;
    }

    public function dashboard () {
        return view('people.dashboard');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $peoples = $this->people->orderBy('name', 'asc')->get();

        //
        return view('people.index', [
            'peoples' => $peoples
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = Validator::make($request->all(), [
            'username' => 'required|unique:users,username',
            'name' => 'required',
            'nik' => 'required',
            'phone' => 'required',
            'photo' => 'mimes:jpg,png,jpeg',
            'password' => 'required|confirmed'
        ]);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withErrors($validation)->withInput($request->all());

        // upload proof
        if ($request->file('photo')) {
            $photo = $request->file('photo')->store('public/users');
        } else {
            $photo = 'public/users/default.jpg';
        }

        // validation success
        $user = $this->user->create([
            'username' => $request->username,
            'password' => bcrypt($request->password),
            'role' => 'people'
        ]);;
        $people = $this->people->create([
            'name' => $request->name,
            'nik' => $request->nik,
            'address' => $request->address,
            'phone' => $request->phone,
            'photo' => $photo,
            'user_id' => $user->id
        ]);

        // if success
        if ($people) {
            return redirect()->back()->with('msg', 'People created successful');
        } else {
            return redirect()->back()->withErrors(['title' => 'Something errors'])->withInput($request->all());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Officer  $officer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $people)
    {
        $people = People::find($people);

        //
        $validation = Validator::make($request->all(), [
            'username' => 'required|unique:users,username,' . $people->user->id,
            'name' => 'required',
            'nik' => 'required',
            'phone' => 'required',
            'photo' => 'mimes:jpg,png,jpeg'
        ]);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withErrors($validation)->withInput($request->all());

        // upload proof
        if ($request->file('photo')) {
            $photo = $request->file('photo')->store('public/users');
        } else {
            $photo = $people->photo;
        }

        // validation success
        $update = $people->update([
            'name' => $request->name,
            'phone' => $request->phone,
            'photo' => $photo
        ]);
        $people->user()->update([
            'username' => $request->username
        ]);

        // if success
        if ($update) {
            return redirect()->back()->with('msg', 'People updated successful');
        } else {
            return redirect()->back()->withErrors(['title' => 'Something errors'])->withInput($request->all());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Officer  $officer
     * @return \Illuminate\Http\Response
     */
    public function destroy($people)
    {
        $people = People::find($people);
        //
        if ($people->complaints->count() > 0) {
            return response()->json(['message' => 'People have some complaints'], 401);
        }

        $people->user()->delete();

        return response()->json(['message' => 'People deleted successful'], 200);
    }
}

resources/views/people/dashboard.blade.php
@extends('layouts.admin')

@section('title')
    Dashboard
@endsection

@section('dashboard')
    active
@endsection

@section('css')
@endsection

@section('js')
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                <span class="page-title-icon bg-gradient-primary text-white mr-2">
                  <i class="mdi">home</i>
                </span> Dashboard </h3>
            <nav aria-label="breadcrumb">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                        <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card card-statistics">
                    <div class="row">
                        <div class="card-col col-xl-43 col-lg-4 col-md-4 col-12 border-right">
                            <div class="card-body">
                                <div class="d-flex align-items-center justify-content-center flex-column flex-sm-row">
                                    <i class="mdi text-primary mr-0 mr-sm-4 icon-lg">drafts</i>
                                    <div class="wrapper text-center text-sm-left">
                                        <p class="card-text mb-0">Draft</p>
                                        <div class="fluid-container">
                                            <h3 class="mb-0 font-weight-medium">{{\App\Complaint::where('people_id', Auth::user()->people->id)->whereStatus(1)->count()}}</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-col col-xl-4 col-lg-4 col-md-4 col-12">
                            <div class="card-body">
                                <div class="d-flex align-items-center justify-content-center flex-column flex-sm-row">
                                    <i class="mdi text-primary mr-0 mr-sm-4 icon-lg">near_me</i>
                                    <div class="wrapper text-center text-sm-left">
                                        <p class="card-text mb-0">Sent</p>
                                        <div class="fluid-container">
                                            <h3 class="mb-0 font-weight-medium">{{\App\Complaint::where('people_id', Auth::user()->people->id)->whereStatus(2)->count()}}</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-col col-xl-4 col-lg-4 col-md-4 col-12 border-right">
                            <div class="card-body">
                                <div class="d-flex align-items-center justify-content-center flex-column flex-sm-row">
                                    <i class="mdi text-primary mr-0 mr-sm-4 icon-lg">done_all</i>
                                    <div class="wrapper text-center text-sm-left">
                                        <p class="card-text mb-0">Responded</p>
                                        <div class="fluid-container">
                                            <h3 class="mb-0 font-weight-medium">{{\App\Complaint::where('people_id', Auth::user()->people->id)->whereStatus(3)->count()}}</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 grid-margin stretch-card">
                <div class="card review-card">
                    <div class="card-header header-sm d-flex justify-content-between align-items-center">
                        <h4 class="card-title mb-0">New responded complaints</h4>
                        <div class="wrapper d-flex align-items-center">
                            <div class="dropdown">
                                <button class="btn btn-transparent icon-btn pr-0" type="button" id="dropdownMenuIconButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="mdi">more_vert</i>
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuIconButton1" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 46px, 0px);">
                                    <a class="dropdown-item" href="{{route('people.complaint.index')}}">See all complaints</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body no-gutter">

                        @foreach(\App\Complaint::where('status', '3')->where('people_id', Auth::user()->people->id)->skip(0)->take(5)->orderBy('created_at', 'desc')->get() as $complaint)
                            <div class="list-item">
                                <div class="preview-image">
                                    <img class="img-sm rounded-circle" src="{{URL::asset('storage/app/' . $complaint->response->officer->photo)}}" alt="profile image">
                                </div>
                                <div class="content">
                                    <div class="d-flex align-items-center">
                                        <h6 class="product-name">{{$complaint->response->officer->name}}</h6>
                                        <small class="time ml-3 d-none d-sm-block">{{$complaint->response->created_at->diffForHumans()}}</small>
                                        <div class="ml-auto">
                                            <a href="{{route('people.complaint.show', ['complaint' => $complaint->id])}}" class="btn btn-primary btn-sm" style="display: inline;">View complaint</a>
                                        </div>
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <p class="user-name">Say :</p>
                                        <p class="review-text d-block">{{$complaint->response->content}}</p>
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <small class="user-name">For :</small>
                                        <small class="review-text d-block" style="color: #9c9fa6;">{{$complaint->title}}</small>
                                    </div>
                                </div>
                            </div>
                        @endforeach

                            @if(\App\Complaint::where('status', '3')->where('people_id', Auth::user()->people->id)->count() == 0)
                                No data
                            @endif
                    </div>
                </div>
            </div>


        </div>
    </div>
@endsection