routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::guest()) {
        return redirect()->route('login');
    } else {
        return redirect()->route(Auth::user()->role . '.dashboard');
    }
});

Auth::routes();

//administrator
Route::group(['prefix' => '/administrator', 'as' => 'admin.', 'middleware' => ['admin']], function () {

    //dashboard
    Route::get('/', 'AdminController@dashboard')->name('dashboard');

    //complaint
    Route::resource('/complaint', 'ComplaintController');

    //people
    Route::resource('/people', 'PeopleController');

    //officer
    Route::resource('/officer', 'OfficerController');

    //report
    Route::get('/report', 'AdminController@report')->name('report');

});

//officer
Route::group(['prefix' => '/officer', 'as' => 'officer.', 'middleware' => ['officer']], function () {

    //dashboard
    Route::get('/', 'OfficerController@dashboard')->name('dashboard');

    //complaint
    Route::resource('/complaint', 'ComplaintController');

});

//people
Route::group(['prefix' => '/people', 'as' => 'people.', 'middleware' => ['people']], function () {

    //dashboard
    Route::get('/', 'PeopleController@dashboard')->name('dashboard');

    //complaint
    Route::resource('/complaint', 'ComplaintController');

});

app/Complaint.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Complaint extends Model
{
    //
    protected $guarded = [];

    public function people () {
        return $this->belongsTo('App\People');
    }

    public function response () {
        return $this->hasOne('App\Response');
    }
}

app/Http/Controllers/ComplaintController.php
<?php

namespace App\Http\Controllers;

use App\Complaint;
use Illuminate\Http\Request;
use Validator;
use Auth;
use App\Response;

class ComplaintController extends Controller
{
    public function __construct(Complaint $complaint, Response $response)
    {
        $this->complaint = $complaint;
        $this->response = $response;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role == "people") {
            $complaints = $this->complaint->wherePeopleId(Auth::user()->people->id)->orderBy('created_at', 'desc')->get();
        } else {
            $complaints = $this->complaint->orderBy('created_at', 'desc')->whereIn('status', [2, 3])->get();
        }
        //
        return view('complaint.index', [
            'complaints' => $complaints
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('complaint.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validation = Validator::make($request->all(), [
            'title' => 'required',
            'proof' => 'required|mimes:png,jpg,jpeg'
        ]);

        // validation fails
        if ($validation->fails())
            return redirect()->back()->withErrors($validation)->withInput($request->all());

        // upload proof
        $proof = $request->file('proof')->store('public/proofs');

        // validation success
        $complaint = $this->complaint->create([
            'people_id' => Auth::user()->people->id,
            'title' => $request->title,
            'description' => $request->description,
            'proof' => $proof,
            'location' => $request->location
        ]);

        // if success
        if ($complaint) {
            return redirect()->route('people.complaint.show', ['complaint' => $complaint->id])->with('msg', 'Complaint created successful');
        } else {
            return redirect()->back()->withErrors(['title' => 'Something errors'])->withInput($request->all());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Complaint  $complaint
     * @return \Illuminate\Http\Response
     */
    public function show(Complaint $complaint)
    {
        return view('complaint.show', [
            'complaint' => $complaint
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Complaint  $complaint
     * @return \Illuminate\Http\Response
     */
    public function edit(Complaint $complaint)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Complaint  $complaint
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Complaint $complaint)
    {

        if ($request->status == 3) {
            $validation = Validator::make($request->all(), [
                'content' => 'required'
            ]);

            // validation fails
            if ($validation->fails()) {
                return redirect()->back()->withErrors($validation)->withInput($request->all());
            }
        }

        // validation success
        $update = $complaint->update([
            'status' => $request->status
        ]);

        if ($request->status == 3) {
            $this->response->create([
                'complaint_id' => $complaint->id,
                'officer_id' => Auth::user()->officer->id,
                'content' => $request->content
            ]);
        }

        // if success
        if ($update) {
            return redirect()->route(Auth::user()->role . '.complaint.show', ['complaint' => $complaint->id])->with('msg', 'Complaint updated successful');
        } else {
            return redirect()->back()->withErrors(['title' => 'Something errors'])->withInput($request->all());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Complaint  $complaint
     * @return \Illuminate\Http\Response
     */
    public function destroy(Complaint $complaint)
    {
        //
    }
}

resources/views/complaint/create.blade.php
@extends('layouts.admin')

@section('title')
    Add a complaint
@endsection

@section('css')
    <style>
        iframe {
            width: 100% !important;
        }
    </style>
@endsection

@section('js')
    <script src="{{asset('assets/vendors/jquery-steps/jquery.steps.min.js')}}"></script>
    <script src="{{asset('assets/js/wizard.js')}}"></script>
    <script>
        $('#location').on('input', function (e) {
            let html = $.parseHTML($(this).val());

            if (html.length > 0) {
                html = html[0];

                if (html.nodeName == "IFRAME") {
                    $('#location-embed').html(html);
                } else {
                    $('#location-embed').html(`<span class="text-danger mb-2">Location format is wrong</span>`);
                }
            }
        });
    </script>
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title"> Add a complaint </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{route('people.dashboard')}}">Dashboard</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Add a complaint</li>
                </ol>
            </nav>
        </div>
        <!--vertical wizard-->
        <div class="row">
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Form step complaint</h4>

                        @if($errors->any())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                    {{$error}}
                                @endforeach
                            </div>
                        @endif

                        <form id="example-vertical-wizard" action="{{route('people.complaint.store')}}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div>
                                <h3>Title &amp; Description</h3>
                                <section>
                                    <h3>Title &amp; Description</h3>
                                    <div class="form-group">
                                        <label for="userName">Title *</label>
                                        <input id="userName" name="title" type="text" class="required form-control" value="{{old('title')}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="description">Description *</label>
                                        <textarea name="description" id="description" cols="30" rows="10" class="required form-control">{{old('description')}}</textarea>
                                    </div>
                                </section>
                                <h3>Upload proof</h3>
                                <section>
                                    <h3>Proof File</h3>
                                    <div class="form-group">
                                        <label for="proof">File</label>
                                        <input id="proof" name="proof" type="file" class="required form-control">
                                    </div>
                                </section>
                                <h3>Location</h3>
                                <section>
                                    <h3>Location</h3>
                                    <div class="form-group mb-2">
                                        <label for="location">Embed location url</label>
                                        <textarea name="location" id="location" class="required form-control" cols="30" rows="10" placeholder="Apply iframe tag here"></textarea>
                                    </div>
                                    <div id="location-embed">

                                    </div>
                                    <a href="https://support.google.com/maps/answer/144361?co=GENIE.Platform%3DDesktop&hl=en" target="_blank">How to get embed location in google maps ?</a>
                                </section>
                                <h3>Finish</h3>
                                <section>
                                    <h3>Finish</h3>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input class="checkbox" type="checkbox"> I agree with the Terms and Conditions. </label>
                                    </div>
                                </section>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/complaint/index.blade.php
@extends('layouts.admin')

@section('title')
    @if(Auth::user()->role == "people")
        Manage Complaints
    @else
        List complaints
    @endif
@endsection

@section('complaints')
    active
@endsection

@section('css')
    <link rel="stylesheet" href="{{asset('assets/vendors/datatables.net-bs4/dataTables.bootstrap4.css')}}">
@endsection

@section('js')
    <script src="{{asset('assets/vendors/datatables.net/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-bs4/dataTables.bootstrap4.js')}}"></script>
    <script src="{{asset('assets/js/data-table.js')}}"></script>
@endsection

@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                @if(Auth::user()->role == "people")
                    My complaints
                @else
                    List complaints
                @endif
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{route(Auth::user()->role . '.dashboard')}}">Dashboard</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                        @if(Auth::user()->role == "people")
                            My complaints
                        @else
                            List complaints
                        @endif
                    </li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Data complaints</h4>
                <div class="row">
                    <div class="col-12">
                        <table id="order-listing" class="table">
                            <thead>
                            <tr>
                                <th class="text-center">Order #</th>
                                @if(Auth::user()->role != 'people')
                                <th>Person</th>
                                @endif
                                <th>Title</th>
                                <th class="text-center">Sent at</th>
                                <th class="text-center">Status</th>
                                <th class="text-center">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($complaints as $i => $complaint)
                                <tr>
                                    <td class="text-center">{{$i+1}}</td>
                                    @if(Auth::user()->role != 'people')
                                    <td>{{$complaint->people->name}}</td>
                                    @endif
                                    <td>{{$complaint->title}}</td>
                                    <td class="text-center">{{$complaint->created_at->diffForHumans()}}</td>
                                    <td class="text-center">
                                        <span class="badge badge-{{getColor($complaint->status)}}">
                                            <i class="mdi mr-1" style="font-size: 11px; vertical-align: middle">
                                                {{getIcon($complaint->status)}}
                                            </i> {{getStatus($complaint->status)}}
                                        </span>
                                    </td>
                                    <td class="text-center">
                                        <a href="{{route(Auth::user()->role . '.complaint.show', ['complaint' => $complaint->id])}}" class="btn btn-info">View</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>


@endsection